In [1]:
import sqlite3

In [2]:

#Connecting to sqlite
conn = sqlite3.connect('example.db')

#Creating a cursor object using the cursor() method
cursor = conn.cursor()

#Doping EMPLOYEE table if already exists.
cursor.execute("DROP TABLE IF EXISTS EMPLOYEE")

#Creating table as per requirement
sql ='''CREATE TABLE EMPLOYEE(
   FIRST_NAME CHAR(20) NOT NULL,
   LAST_NAME CHAR(20),
   AGE INT,
   SEX CHAR(1),
   INCOME FLOAT
)'''
cursor.execute(sql)
print("Table created successfully........")

# Commit your changes in the database
conn.commit()

#Closing the connection
conn.close()

Table created successfully........

In [7]:
import sqlite3

conn = sqlite3.connect('example.db')
cursor = conn.execute("SELECT * FROM EMPLOYEE;")
results = cursor.fetchall()
print(results)

[]

In [14]:
# https://datatofish.com/create-table-sql-server-python/
#https://stackoverflow.com/questions/36028759/how-to-open-and-convert-sqlite-database-to-pandas-dataframe

#Connecting to sqlite
conn = sqlite3.connect('example.db')

#Creating a cursor object using the cursor() method
cursor = conn.cursor()

cursor.execute('''
    INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, AGE, SEX, INCOME)
    VALUES
    ('Jade',20,'London',1.1,1.1),
    ('Mary',47,'Boston',1.2,1.1),
    ('Jon',35,'Paris',1.3,1.1)  ''')

conn.commit()

In [15]:
conn = sqlite3.connect('example.db')
cursor = conn.execute("SELECT * FROM EMPLOYEE;")
results = cursor.fetchall()
print(results)

[('Jade', '20', 'London', '1.1', 1.1), ('Mary', '47', 'Boston', '1.2', 1.1), ('Jon', '35', 'Paris', '1.3', 1.1)]

In [18]:
import numpy as np
import pandas as pd

df = pd.read_sql_query("SELECT * FROM EMPLOYEE;", conn)
df

  FIRST_NAME LAST_NAME     AGE  SEX  INCOME
0       Jade        20  London  1.1     1.1
1       Mary        47  Boston  1.2     1.1
2        Jon        35   Paris  1.3     1.1

In [19]:

#Connecting to sqlite
conn = sqlite3.connect('sql_1.db')

#Creating a cursor object using the cursor() method
cursor = conn.cursor()

#Doping EMPLOYEE table if already exists.
cursor.execute("DROP TABLE IF EXISTS EMPLOYEE")

#Creating table as per requirement
sql_1_created ='''CREATE TABLE TabelaA(
   Nome VARCHAR(50) NULL
)'''
cursor.execute(sql_1_created)
print("Table created successfully........")

# Commit your changes in the database
conn.commit()

#Closing the connection
conn.close()

Table created successfully........

In [20]:
#Connecting to sqlite
conn = sqlite3.connect('sql_1.db')

#Creating a cursor object using the cursor() method
cursor = conn.cursor()

cursor.execute('''
    INSERT INTO TabelaA (NOME)
    VALUES
    ('Fernanda'),
    ('Josefa'),
    ('Luiz'),
    ('Fernando') ''')

conn.commit()

In [21]:
conn = sqlite3.connect('sql_1.db')
cursor = conn.execute("SELECT * FROM TabelaA;")
sql_1 = cursor.fetchall()
print(sql_1)

[('Fernanda',), ('Josefa',), ('Luiz',), ('Fernando',)]

In [22]:
import numpy as np
import pandas as pd

sql_1 = pd.read_sql_query("SELECT * FROM TabelaA;", conn)
sql_1

       Nome
0  Fernanda
1    Josefa
2      Luiz
3  Fernando

In [23]:

#Connecting to sqlite
conn = sqlite3.connect('sql_2.db')

#Creating a cursor object using the cursor() method
cursor = conn.cursor()

#Doping EMPLOYEE table if already exists.
cursor.execute("DROP TABLE IF EXISTS EMPLOYEE")

#Creating table as per requirement
sql_1_created ='''CREATE TABLE TabelaB(
   Nome VARCHAR(50) NULL
)'''
cursor.execute(sql_1_created)
print("Table created successfully........")

# Commit your changes in the database
conn.commit()

#Closing the connection
conn.close()

Table created successfully........

In [24]:
#Connecting to sqlite
conn = sqlite3.connect('sql_2.db')

#Creating a cursor object using the cursor() method
cursor = conn.cursor()

cursor.execute('''
    INSERT INTO TabelaB (NOME)
    VALUES
    ('Carlos'),
    ('Manoel'),
    ('Luiz'),
    ('Fernando') ''')

conn.commit()

In [25]:
import numpy as np
import pandas as pd

sql_2 = pd.read_sql_query("SELECT * FROM TabelaB;", conn)
sql_2

       Nome
0    Carlos
1    Manoel
2      Luiz
3  Fernando